@startuml
skin rose
package "user statistics" {
  [UI]
  [data collector]
[data aggregator]
}

database "database" {

}

[UI] <- [data aggregator]: send aggregated data
[data aggregator] <- [data collector]: send user data
[data collector] --> [database]: read user data

@enduml
