@startuml
skin rose
package "user statistics" {
  [UI]
  [data collector]
}

[data collector]

database "database" {

}

[UI] <- [data collector]: sends user data
[data collector] --> [database]: read user data

@enduml
