[book]
authors = ["Gergő Pintér"]
multilingual = false
src = "src"
title = "handout"
description = "software engineering"

[rust]
edition = "2021"

[output.html]
git-repository-url = "https://github.com/pintergreg/software-engineering"
site-url = "https://pintergreg.github.io/software-engineering/"
mathjax-support = true
# additional-js = ["quizdown/quizdown.js", "quizdown/quizdown-init.js"]
additional-css = ["assets/custom-mdbook.css"]

[output.html.fold]
enable = true
level = 1

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
