self_contained: false
bibliography:
    - "references.bib"
    - "wikipedia.bib"
citeproc: true
csl: "../assets/ieee.csl"
mathml: true
reveal_url:
# reveal_url: "http://127.0.0.1/reveal.js-5.1.0/"
assets: "../assets"
