@startuml
skin rose

object deck {
  description = animals
  id = 17
  words
}

map "map: Map<String, String>" as words {
 dog => kutya
 cat => macska
 fox => róka
 lynx => hiúz
}
deck::words --> words
@enduml
