gitGraph
    commit id: "Display avatar #17"
    commit id: "Display username #18"
    commit id: "Add progress bar #19"
    branch "feature: activity"
    checkout "feature: activity"
    commit id: "Add activity matrix #20"
    commit id: "Set color map to Greens #20"
    commit id: "Display labels #20"
    checkout main
    merge "feature: activity"
