@startuml
skin rose

package database <<Database>> {
}

package UI #efefef {
  class GUI {
    drawProgressBar()
    drawActivityMatrix()
    loadProfilePicture()
  }
  class AggregatedData {
    String name
    Integer id
    DateTime registration
    Float progress
    List[List] activityMatrix
  }
  class ServerConnector {
  }
  'note as n
  '  different codebase
  'end note
}


package UserStatistics as us{
  class UserData {
    String name
    Integer id
    DateTime registration
    List activities
  }
  class Activity {
    DateTime timestamp
    Integer lesson
    Result result
  }
  Enum Result {
  }
  class DataCollector {
    readUserDataFromDatabase()
    sendData()
  }
    class DataAggregator {
    calculateProgress()
    calculateActivityMatrix()
  }
  class AggregatedData {
    String name
    Integer id
    DateTime registration
    Float progress
    List[List] activityMatrix
  }
  class ClientConnector {
  }
}

UI.AggregatedData -up- GUI
us.AggregatedData -up-* DataAggregator
DataCollector <-right- DataAggregator
'DataAggregator --> GUI
ClientConnector <-right- ServerConnector
us.ClientConnector --> DataAggregator
ServerConnector <-- GUI

Result -left-o Activity
UserData o-- Activity

DataCollector *-- UserData

DataCollector -left-> database
@enduml
