@startuml
skin rose

package database <<Database>> {
}

package UI {
  class GUI {
    drawProgressBar()
    drawActivityMatrix()
    loadProfilePicture()
  }
}
package UserStatistics {
  class UserData {
    String name
    Integer id
    DateTime registration
    List activities
  }
  class Activity {
    DateTime timestamp
    Integer lesson
    Result result
  }
  Enum Result {
  }
  class DataCollector {
    readUserDataFromDatabase()
    sendData()
  }
    class DataAggregator {
    calculateProgress()
    calculateActivityMatrix()
  }
  class AggregatedData {
    String name
    Integer id
    DateTime registration
    Float progress
    List[List] activityMatrix
  }
}

AggregatedData .right. GUI
AggregatedData -up- DataAggregator
DataCollector -right-> DataAggregator
DataAggregator -right-> GUI


Result -left-o Activity
UserData o-- Activity

DataCollector -- UserData

DataCollector -left- database
@enduml
