%%{init: { 'logLevel': 'debug', 'theme': 'base' } }%%
    gitGraph
       commit
       commit
       commit
       branch feature
       commit
       checkout main
       commit
       commit
       checkout feature
       commit
       commit
       commit
       checkout main
       merge feature
