@startuml
skin rose

package "logger" {
  component "scheduler" as s
  component "database connector" as l.dbc
  component "bluetooth connector" as btc
}

package "frontend" {
[plotter] as p
[template engine] as te
[web service] as ws
[database connector] as f.dbc
}

database "sqlite3" as db

l.dbc--> db
f.dbc --> db
s --> btc
s --> l.dbc

ws --> p
ws --> te
ws -left-> f.dbc
@enduml
