@startuml
skin rose

class Shape {
}

class Square {
}

class Circle {
}

class Color {
}

class Red {
}

class Blue {
}

Shape <|-- Circle
Shape <|-- Square
Color <|-- Blue
Color <|-- Red

Shape o- Color
@enduml
