direction: up

ldb: load database
gg: generate groups

ca: create app skeleton
dp: display progress
dc: display card
rm: reveal meaning
sn: show next
us: update state

gg -> ldb
dc -> ca
dp -> ca
rm -> dc
sn -> gg
ldb -> ca
us -> dc
