# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
        branches: ["main"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        runs-on: ubuntu-24.04

        steps:
            - uses: actions/checkout@v4

            - name: install dependencies
              run: |
                  sudo apt-get install -y ruby pandoc npm
                  wget -qO mdbook.tar.gz https://github.com/rust-lang/mdBook/releases/download/v0.4.41/mdbook-v0.4.41-x86_64-unknown-linux-gnu.tar.gz
                  sudo tar xf mdbook.tar.gz -C /usr/local/bin mdbook
                  mdbook --version
                  rm -rf mdbook.tar.gz

            - name: compile presentaion
              run: |
                  cd lectures
                  ruby build_slides.rb
                  cd ..

            - name: compile handout
              run: |
                  ruby build.rb
                  mdbook build

            - name: compile mindmap
              run: |
                  npx markmap-cli -o lectures/mindmap.html --offline --no-open lectures/mindmap.md

            - name: build mock exam
              run: |
                  cd lectures
                  ruby build_mock_exam.rb
                  cd ..

            - name: copy slides
              run: |
                  mkdir -p book/slides/figures
                  mkdir -p book/slides/assets
                  cp -r lectures/figures/* book/slides/figures/
                  cp -r lectures/*.html book/slides/
                  cp -r practicals/*.html book/slides/
                  cp -r assets/* book/assets/

            - name: deploy
              uses: peaceiris/actions-gh-pages@v4
              with:
                  personal_token: ${{ secrets.PERSONAL_TOKEN }}
                  publish_dir: ./book
